# Generated by Django 4.2.5 on 2023-10-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_recordtransaction_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordtransaction',
            name='transaction_date',
            field=models.DateField(auto_now=True),
        ),
    ]
